package:
  name: r-biodb
  version: "1.0.1"

source:
    #  url: https://github.com/pkrog/biodb/archive/v1.0.1.tar.gz 
    #  sha256: 661508c2e42f34b68a99a9fc2e0f55bb080aa6cad11713564874e6d2dbbebb2f
  url: https://github.com/pkrog/biodb/archive/hotfix/cpp_build.tar.gz 
  sha256: 46688af520926dd487d6796fa2050d4778f58a4e8242df44b6da51636e455482

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
      - gcc  # [not osx]
      - llvm  # [osx]
      - r-codetools
      - r-devtools
      - r-rcpp
      - r-xml
      - r-stringr
      - r-plyr
      - r-bitops
      - r-rcurl
      - r-r.utils
  run:
      - r-rcpp
      - r-xml
      - r-stringr
      - r-plyr
      - r-bitops
      - r-rcurl
      - r-r.utils
      - r-jsonlite
      - r-digest

test:
  commands:
    - $R -e "library(biodb)"
    - $R -e "library(biodb) ; biodb = biodb::Biodb()"

about:
  license: AGPL-3.0
  summary: 'An R package for connecting to chemical and biological databases.'
  home: https://github.com/pkrog/biodb
