package:
  name: r-biodb
  version: "1.0.1"

source:
  url: https://github.com/pkrog/biodb/archive/v1.0.1.tar.gz 
  sha256: 661508c2e42f34b68a99a9fc2e0f55bb080aa6cad11713564874e6d2dbbebb2f

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library(biodb)"

about:
  license: AGPL-3.0
  summary: 'An R package for connecting to chemical and biological databases.'
  home: https://github.com/pkrog/biodb
