{% set name = "centrifuge" %}
{% set version = "1.0.4-beta" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 4

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/infphilo/centrifuge/archive/v1.0.4-beta.tar.gz
  md5: 1c31b7b3c88094c007c5d5b2336e4196  

requirements:
  build:
    - gcc   # [not osx]
    - llvm  # [osx]
    - zlib {{CONDA_ZLIB}}*
    - perl
    - python
 
  run:
    - libgcc  # [not osx]
    - zlib {{CONDA_ZLIB}}*
    - perl
    - python

test:
  commands:
    - centrifuge --help

about:
  home: https://github.com/infphilo/centrifuge
  license: GPL3
  summary: 'Classifier for metagenomic sequences.'

extra:
  identifiers:
    - biotools:Centrifuge
    - doi:10.1101/gr.210641.116
